name: Build macOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: pip install pyinstaller
      - run: pyinstaller --windowed --onefile main.py
      - uses: actions/upload-artifact@v4
        with:
            name: MyApp-macOS
            path: dist/*.app
